### ISSUE TITLE
Add Previous Events to <•> JavaScript section

### ISSUE THREAD

**Issue by taras** [this-dot/thisdot#49]
Currently we have Upcoming Events but we do not show previous events. We should make it possible for people to access previous events from any <•> JavaScript page.

Make it look like Upcoming Events but with Previous Events title.

<img width="1129" alt="screen shot 2017-02-08 at 11 51 44 am" src="https://cloud.githubusercontent.com/assets/74687/22725733/498d5422-edf5-11e6-960d-1e06803c7635.png">

## TODO

- [x] Link to event page
- [x] Add call to action button: "watch"

**Comment by zinyando** [comment]
@taras which page should the "Watch" button point to. Right now there are no videos. Can I just point it to the youtube video?

**Comment by taras** [comment]
No, just point to Contributor Day page for that event. Video will be added
there later.

-- 
Taras Mankovski

**Comment by zinyando** [comment]
This.Javascript doesn't have a contributor day page. Where should I point it to in this case?

**Comment by taras** [comment]
Sorry, my bad. I meant to its corresponding page on this for sure.

-- 
Taras Mankovski

**Comment by zinyando** [comment]
I added a Previous Events section to https://www.thisdot.co/javascript page. If we were on any other page I would have linked to that url but since we are already there I'm not sure where to link to. Maybe for now just link to the same page?

**Comment by jorgelainfiesta** [comment]
Hi Lennex, I changed this task to assign it to myself on Basecamp but forgot to tell you. I'll make this task because it requires to design the "Previous" event layout. I'll submit a PR today.

**Comment by jorgelainfiesta** [comment]
The design for previous events is now live.
