### ISSUE TITLE
thisdot.co/javascript still not the right time. is it the same india timezone issue?

### ISSUE THREAD

**Issue by ladyleet** [this-dot/thisdot#55]

**Comment by ladyleet** [comment]
<img width="1048" alt="screenshot 2017-03-01 21 56 59" src="https://cloud.githubusercontent.com/assets/8270563/23494846/094f9e02-feca-11e6-81fb-c8c048033cf1.png">

should be 9am PDT.

**Comment by ladyleet** [comment]
@taras @jorgelainfiesta ^^

**Comment by jorgelainfiesta** [comment]
We had it stored as 9:00am PST instead of 10:00am PDT or 8:00am PST. A fix is deployed but cached versions are still running around for now.
